---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    password: AgA+0SiVPr+c9c/rMKrjgYzTO6Hk4+4FhbY8EWtnBbcz4+h+n1B7p2hf0E/aj6FFvWapfFV9/tbSLlxADJUVbPNm3C2ZJA+vk4WPQrEx8RjPyExqqx6WCx/AaD8cccWpkOAvK9DceRILzZn46jDJ3SBSa1Hh7VIIKcAXdFjR8OeZ21RH+MyYNbKWHFukzXq7sRHwnaDn9qkd8OC5ygDFbRjLfwMigZIiLuMtijuCFgtRkbJOyQsZjrrncNDBIhtN8xap0tjIimhkW8TzP7MC8zad5WArkHIjLEywLksZFeQewfBGpOHbFQin+DJ/00FvhHbNhmXR1Ktnb8v3MTxzXmYmO7iDmbEm/LCieNcqH61Ly5LyQfnDOcwynGtnKRSRTM8PAt0ki4URIK8b6nXPxzKXk0bl7FG4nRr+fmTRS8QvGxfkuG22Dh8RVt47MvO3qjnYPk0JEHcfDi08zTYAJi8OPNYPMmnogYGg4KhF+8Zjv96+pOADvP2WaXsLK05+IHAsY6NUxFTmRMDyJzPfpz6opJwN2sn9mJ0nJycQjz7yx04TLgFTjWRxeSd4OxdAhLAMAN2ZVz98Jbbgw7FOViiyOF/5BogTm0sRx7vOyDaQmxQmtmiJQFelczG1tPRqMvCCpFFt86Bqsb09BUH5bxdRBgeAXm4xu7cQ/gk3K6kwgfulyjkpJlgcy8Cc2887aqowMWJgGcglu3U=
  template:
    metadata:
      name: redis-auth
      namespace: redis
    type: Opaque
