---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCjgmRIqlqWjmLaqipjlh0XPXV1JnRjEOnp3vkB8j9ul0XB9P5pzWEedI0sZ9Bw3I+yiFlKI6Ncet0XxLgGvxf5vzfbecZmADLgt0bRBxZ0/5IWvI5zVO2UGXSBkeGzqRKtakzCbur/BDplw99hqZ6IQ6ZYwU+vBHtsEnAMwuSOTlYWihqvEuoTuNUg4UIocJqya/a8+69OBBMjQbntrCHuFGGAVi6pUO65duSFa22QAv3HLus0b9V+/UxrTt9at5IO8t1NZ9PxA0QXOghal08Pyyx6elSBrMzKoY2jVrYqmoT7CkHghqh3MoxIhnbnR+r6JTqKeKOLbLLnfoPYiadhFwZVsMlQrXyRAqTDnBtP8sCCRfun0oRI0w0Pv3ZopmVHovlID/g5YMUvrtdx8zjfBKD6gbOx5X8sAXfBSi5gClXJ7tyudTBmfb/d/Q+1ixHwjxSteDb6zUlWjSkJ/gHiy/M/VVYtRCsKymNhbPaUYE+RFz/dnrZDD1Q1UQJ1d57Bfe56CGyd+2iMHmBUUMmDFzfEaDUbYHns8RVANg5C/wfI7c0QGv48ndx+H1GBbLABs15NBcTck+5sFFp7PpFYokj28ULRnDSE24B0DgGJWm4sBtnEKmr2IzM1DuUWhVFUDgIptZu8CEhNNrD7s/3biJlG0LZ5Yw/WM6VRVcdSCC1pYrgEwQeaq29zkgJETPgQG1tbnsJdRVm+ZgdPToPb2bCb6DlJIR4kfd/pmbrDv7VTrvMgO77wgZq359cIeRGl8YpR2UwwmTo6N3SwZQG5tL8ypRPXV9AVkzxhYyD72D4ipZc6vFIieOFd3t+f3ovEhDq58DE4XjOtWqYjO8gqXjGalgd1AkaV/XP+oqVG
  template:
    metadata:
      name: harbor-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
