---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-secret
  namespace: jenkins
spec:
  encryptedData:
    .dockerconfigjson: AgCIKaAYHZ1BREpN3ngP0VCpvs7SYpPJxeNa0QO7xbgWn8NFGOiUxv8nhPtoFLFY5KfWzjEl1CaJSGII1P3JYpM80DTzxYPoN/C7qVBiBagRcmwzjf5a5xFM4IlxcB5wzviIY4h/4Xsihnz8jl9T63dJ3FnDs3JCK4Q2Ff2F2FnBYxLdnXjXYaxVV+bHPYB608zv7B1r9Aj8sOXveMoV5kAFCWdyfEnNVk6PBkovaB0SL2HyayXw2sPm8uyv1G4xVbP9wEAWAhcuaNl1qFXmW/0m9+pGbdukbYs0pVTZXJwi3y7QOwYFnmVntmvyBpNR+s0IrPrWKhkIheaOri9vHA1qjW9O1RuZ4GJAEKQVxyCDdDNr29KsQst+JMu8yDWuscTR/MICTVqCctoo1gIEGjnIbTzpMmZ55VBR9PR5fL5xpkCPMCkEFjhNdCi5so/OUBjuM2RWMplBZh3ZHXJoIM9aSp/n/SrWy/fn124diwPZNES/W8QzQfU4eoht84CkvOj67cUleajkgW0p0EnREXQ5SQIIsPh0ra5brxjBjMTayDGVJsTOLAUizjoHokAucqkKIA6Igr6Ccz9vQQi7sDx1xfUHMlW6Vi03/emR9d+zigVJboBs7njDpBWJwiQttuIjkdPchkPHYWgH+QSXQCIZazV6NqrGC2hrdeMfmzico1IJJvYvSeDV2mokmUVW0+JB2NT0Py2ACRK+5ik+K2J37FJR3VV+F0b8E2SbeIFKFM3x2kqfp6XDayWqa2DMkLhYJtHRNnMHdSKJiUpKKJdSOrXS154P9fVJTltmX+zNHCugs9ROcTe6eesUzq0rhNhlFbwge/R9COnGl5wfNVMf285HFaQ01D8563BLBguuEREw9gz2mFAHv1/yMp1k0rRO3no4BA==
  template:
    metadata:
      name: harbor-secret
      namespace: jenkins
    type: kubernetes.io/dockerconfigjson
