---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kaniko-docker-config
  namespace: jenkins
spec:
  encryptedData:
    config.json: AgAbUlK11hlpdsnWDdiL55I/ENBdpK64W4IPGAkmIOQO+6Dq385BrS/D98fSNPZ0CTqNGefxpdIZjsskVpo86EmDzD2heKYQAC4yY+Y92+H7upD5U4TL1Ud3vxdigN0XcM9yIBNATlRIfFVwxz+WMXq6hZzN+Hhx/YHw//URk9MAZgBCaPbPuGJyB1FwfCFWly+zV6Xtt8DumsCsoTgGdlvjI7ITE2fW6xZiu8/dFqFJ9Vm83APm2HfiEbTJEyOkPg53vdg+84fMBbT+SgPB41PZbiXEXAU687JCpIaVFrwyd6bSzN6ZbSbhF7iCV3vA3MAYlelVck3xErXGNrN+97TplJkSdXkXZVqOCLt/Gl1fttU6p98RUp8KyM8raAsZ8K15zrSO1OhzkfSjWT3Mirfw0UU/JhV79J99UeHMhNt7RvO9hIBhszqD7n2R1EcPUS/WSWv5VDZ6HTU039ijPPDpn5ME+EKMDSKJV6yu4AfexxzsFsITTCrRTrHXTV3Dq4SMGRw9xf0XSOR5DS/83QO4Fr3+FUqjg8BNVxp4z0d2di5FVRv1jFzZJDTL2r0x47FAfS/j3+rdCdgBmgulzW/m68PBt5erOVp8jYMm8NqvgWJxtvtl0Mu0zvPY3tZyGZJUlxyDotRN5JVmfmQUKEb0fanBhMmLz/eOrVDi0+xAVuvov+eOrpGcQ06Z19b/IOM5fGhg6oSORU00gVfpKV5/qjRi3rOLVdFPRkYE6RFxIUu/SYftU8jS/XcxRcEoig1oiIdXZRPx9LtmdEnU0bJWG8ZQI/fa5kYUKzm17dM750DI95s3
  template:
    metadata:
      name: kaniko-docker-config
      namespace: jenkins
    type: Opaque
