# infra/sealed-secrets/sealed-secrets-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://bitnami.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.19.1
      helm:
        releaseName: sealed-secrets
        valueFiles:
          - $values/infra/sealed-secrets/sealed-secrets-values.yaml
    - repoURL: http://linux03.local:3000/admin/gitops-lab.git   # align with your existing apps
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      # NOTE: no prune — this app owns the SealedSecret CRD
    syncOptions:
      - ServerSideApply=true