# infra/secrets/secrets-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://linux03.local:3000/admin/gitops-lab.git
    targetRevision: main
    path: infra/secrets/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      # no prune for now — enable after migration is verified stable