apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: "0.16.0"
      helm:
        valueFiles:
          - $values/components/metallb/metallb-values.yaml
    - repoURL: http://linux03.local:3000/admin/gitops-lab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:                      # 临时注释, 验证 diff 后恢复
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
