apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: shared-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway     # must match ingress gateway pod label
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.local"
    - port:                        # new: HTTPS 443
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE               # TLS terminate at gateway
        credentialName: local-tls  # secret must be in istio-ingress ns (copied in step 1)
      hosts:
        - "*.local"
