apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins
spec:
  storageClassName: longhorn
  volumeName: pvc-d55b9d54-61ba-4b80-8b2e-395fc395d884 
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
