---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: elasticsearch-exporter-creds
  namespace: logging
spec:
  encryptedData:
    password: AgANJtKYqNF1/fR8P2htz2AX4Gjm7kwabY2jpmAUTKRd0GbXd+nWMR2qLXt1/LK+CAEv2R/rvUbseIk2Do4SRnpYOgIg+Z3aQw/w1jtUJLlULltec3oxbfFwIjr3bAJHTA2bmR87/JIORScmLIIkpRlnPpTzFJTtVJ00+e6K0lisvO0bXta4MltgkW8x/U4z95+JbHOyfKAUKDWvaiwPihkhRlNZCjNC4PVjUKg8JWK7o4B55MREpinOydMjbKSKxJCf4h+/ufKcFXt0ZemKO7meVfQF5X6WSRFe5cjb7lRE8GUvKA97S0H6CaVBPzwfAqJCjxW1Xo3qx/1UTby7VpBEp3ntDecEefl3Ll7prgjIVlBYVH2Yi28y6XOWzNcPzqA2kX4QWHh6NL2I2UBkoj4nNWYptMtLqodO4VogodKuWos7ci3aF+sqiL7ZEQwvUGdl6wx4P/CBiz15UxEJW6comY6u0f+0d0VD9Km+ecq/hxMOw8lUV0AP4Aq7fI7M0SRRmn5F+61eun0M3FWX5iGQO/M9pP345idZLigfyqErOAtKS5DKy299EMP3UlLWibgsCFHJJS/h7i0mL7XAXMHafU/aq1EKvxQuTj9OVZu8II81xsM0qJw5bHnFmNoKPEQyoRZ712AKp04urBuNC9EImrke82JwZ0JzP2JPnL5bGD9x5bvRDdjosqmMqCMhZn3VlDacXActJkvxHAY9vKsRadO8DFCKGEQ=
    username: AgCnE2okXdrJhqwrMlydJozcSBNyJEsiXe22KJx3yipjqEdIa099CewyXcLd3pU0lSjiedcc+g7NKG2StcsP/mxRXVwwbbv8qhzQCGGB9mqRuWx/111iKE+hOmXCbUspfWRDPV/fDXlnbNNx8JqSfCaZWyroc5kBxuvlJg2CGoumcCPDVvPfU6u9ChPC3eplXoHingIwyRJJRvlMt6JSjLT7JvYwy7NMsukJgAEWsjxo6zoIWqP0jwKeD/sa2v3f+Tvp4B2RYx94/BDG30Jcse2v8DCHjvpxGAAuz16Ees3vecKT+JQanQO3WM99KB1rWCzXAoH5sL3CwmggY79FndzwxrLqzteaboIJksiTq5ET76gp5qs+Vli88NFiVCgCeEzOf41KTIxpbBuUpYiDfieo+DexihMpW7gEIUDCUGg4JLhq+YyhFlhI0IL2xh5aV6Vh+OHmYcC0RoZRNu8YtRZCb77wmiDhPVps6z0vapUdI5/xRstlOjuwY3eQ7m4qhks6Ge+HLJ04qpSFV7PWDKEk6VhOvcpJYHl4gH8m9KEQg9BdEQmqda/xqDwbD5e4j0pwyPvl8408LbqNPACvltCBW6diZVLpdRb+a9ylKAYYOWUVb2TkXNQcFJnwCOQo8ZyLdB2Atr08xvNh7YcVWfSwQUdXX0rdza7IdqiFfxSFqvREJfDTHkd0bZQwpSQQz6CTEhdpEnQG
  template:
    metadata:
      name: elasticsearch-exporter-creds
      namespace: logging
    type: Opaque
