apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-demo-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://linux03.local:3000/admin/flask-demo-2-chart.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: networking.istio.io
      kind: VirtualService
      jsonPointers:
        - /spec/http/0/route/0/weight
        - /spec/http/0/route/1/weight
    - group: networking.istio.io
      kind: DestinationRule
      jsonPointers:
        - /spec/subsets/0/labels
        - /spec/subsets/1/labels
