apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://linux03.local:3000/admin/gitops-lab.git   # your Gitea repo
    targetRevision: HEAD
    path: manifests/redis        # directory mode: apply all YAML in this dir
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   # safety net, though namespace.yaml also creates it
