# platform/snapshot-controller-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    - repoURL: http://linux03.local:3000/admin/gitops-lab.git
      targetRevision: main
      path: manifests/snapshot-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system    # controller manifests target kube-system anyway
  syncPolicy:
    syncOptions:
      - Prune=false           # owns CRDs
