apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      chart: eck-operator
      targetRevision: "3.4.0"
      helm:
        releaseName: elastic-operator
        valueFiles:
          - $values/infra/logging/eck-operator-values.yaml
    - repoURL: http://linux03.local:3000/admin/gitops-lab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
