apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-elasticsearch-exporter
      targetRevision: 7.4.0
      helm:
        valueFiles:
          - $values/infra/logging/elasticsearch-exporter-values.yaml
    - repoURL: http://linux03.local:3000/admin/gitops-lab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
