---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-creds
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgB5VRrhhu2rt0urfyt07l0A7Mquowc5r8qtQYRJf0CAEB8Ob+LBepdQXAeFfHij48G0jUUCzwbsrSQuR5VjNlWYLWZMlQpBPBIg5PyjRd85WiNd2YtOVaqVKgK02vxfJuwpjyDLHogSoDyOuXaR5PT1ZhA42FcnEAOp0rueGRd2fvsMMZjQHidCIxsRUXTp9AD5+pX64q06yRhlkcriUAhDG3U1gYQTkOrCQ6kLN14oRnuyVaw4BvTVww/SfZiTUokU92HA0AN0N/Xt5LDGjYHbShnouioDndqn3biZz7wr24RDXxE2MROpIVzzBxIYwQ81xZOAlIshRblquVRlRsmh2xUJvGzGtWZt4COpcwB9p52RvVDpH5MUzucovEq44Epbe/p1Hioc2D9K93Iy48AHHu6v1Pkn3MfNbI8moPPS9E7oFDQTR/n9OKrm4hKfLWlH2pIg/tHSGbAWH15yk0GY5q1urpj3oboYc2m9jdUNVMh8gEP7dstiV3ObvipEHjVXN5FSAOjZNwCGDSjw9FMkZ//7NwP0si59fBnmfUursKp8QE+pR22Irm1bGbn9u7dMPcyjgmMmubwMcQWl/YfTstgBWcXijER5PvHiTlnKHXJclwu92s5pg7seMIO236KgYa5Qm3066oE4taopUiEUdAgTR3SQ/CwzqA5sgVQWnUJwWwCI3VakKL2ca3b42sdJzQNI1GpLDsniidcyW+DK9REB/scPQzli2jaueN0sihkSuDyTCc/3eYAV6f0b1h0KtMCXxOxFmcs7m5Tf5U1KsWTMxTe3od8DgIo8ytByVBLXqx6KZj5XdofbtQ4AbIgsU6ymzhmeFzTo0+BKs5Rrh2B3Yn9eSLJ1W4rw2t2LWCLl/A0ler0LFBZ2w6EOdGliFvRkQmGbRQbyYqU7L5Zp3J38dROpldZ69pnj0siYNnmYjTgYozsMDoVkll+HZo/yYgdgIgIDDuwOBp5K
  template:
    metadata:
      name: harbor-creds
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
