---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: repo-1003332605
  namespace: argocd
spec:
  encryptedData:
    type: AgBofwMgZDLxsuzujYF9Ij6pUQszPX8glWxijBSpGh+9lZXqXzMDuTakzJZNjU0crwiV76s1yAvtzHmLc6PF9e5xsPM9aSdSsF5k39GYUZqzoFWU0D2MBWfqSiS0A41QAuWLW5fNT8C7l9wugkThQPAomrq+PiWlD3XbIuvUMZ/sZsQdmLnbzAkSL9zcvsEjGR1WYPb+SjV1NutauH3sCFc4WmlwFDwwV7m35TO744ovcnOTSWg2G2sy3zkPMWCqufTovK9QufYftBClHj83u4P1or+d/HxTsbbGi0pZ5qtVNSfFJ4GyKmk1ExIcMDRg2ulmd/Km00h1uo8WirWiPgrQO/v+f65GlpvT+y6Qhf1Mik4jo54jT3O2XygYCZNbENn4uvrTht07j6rEZAp1XoFLnKGIRIoqf8oYz8/LJ09rtXp0UGcB7JveDlzKayMLMBJNirENbZYSeP2ZRKm7emcLDNX0fyK53yVm+aRHdtlg8AdAQSnxwNfPqDcggnHshmWGja1jRapU7/YePLzs4GW3o6YduuPfY7MpfMLW6wlNWlefvQ//b+TomvBzSfodqOPU6wbl3gfqpKCTk9n2rW2leWtpFgQZ2b2DP3N6JoFsLNAN9YXXmWNCrI+0LJgrevZ8rp7xQIjgw6GfQ0pGhrQ+d932W52ITAhl/9QpMt6vwVCO9BYjxP0wpdfmQpa1Tz2AksM=
    url: AgCWkRo22gdsj/l07k7Eo4BVNvbWo4mu/40E+VxpNHjo7mQyyEV61tSgzJeYJRl84ZAd9JQqjvt1I4cXxuD8Gu7pwu2Lr3dedk+cXOWbilZY/EzpewE9tvmak0WGOgvvw2r0Y5oQCGjzy1Zt3I3x9yuXtlX7JyBbq4fwJ9LxEjuo4Yh+OYlvglohPlKoBZSfMqyQcSPTzSJzCHfz4AOncKE9D96aXwM26jftymuSQdE+B+DMjAOrjJtZyWREWBqPwuI6lT4IS1c8+sWaMQOiKjTlh/iNySm51eWv3YrEsqWBIHkm0XTYZq0+F6RcTIr7sNGCcDmAQZrdAdXwaZgutwMDpmtio0GwnTbtY13Op2b0w8Gp7QPi+HZ2GzWfkGahUQ1h8Pz9OPPo1q/7H8wL1heoZ03Y7Cwuv7ioY0LShS9aeuoZsN3KKonaTntLIZP6qGqJtlJJr2w8+OXHKdSp1hyayCtwyrAs2nfAId12DIvTU5D44ZjGBYDVmWOfbRox7TSHWCJPwbJEPkMvGWHhKK+R157MEKi5cQ88K20j848IWooCUmm+SBbPmM19yz0smyg4LV1+8tygDQl5Fij7hKdQahHO0b3+56IgbKcN2vuCEOjsWDizO7M/jqopxN+9AJDKvSaYgLJChncnDadFzh8jFitpTt9e5g9ob3dW5TDdpRnGiQ2wjEZUhIv3Xi1MznEASlN/El22eICF1VqzUbbJ2B5vy9QQfkrm+KIiZ4RuqrgGhV/lL4S+QH1VxP1a
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      labels:
        argocd.argoproj.io/secret-type: repository
      name: repo-1003332605
      namespace: argocd
    type: Opaque
