apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: flask-demo-1-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: "git"
    gitConfig:
      # Gitea repo (note: http, not https, unless you fronted it with TLS)
      repository: "http://linux03.local:3000/admin/flask-demo-1-chart.git"
      branch: "main"
      writeBackTarget: "helmvalues:/values.yaml"
  applicationRefs:
    - namePattern: "flask-demo-1"
      images:
        - alias: "flask"
          imageName: "linux02.local/myapp/flask-demo-1"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^[0-9]{14}-[0-9a-f]{7}$"
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
