apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
data:
  redis.conf: |
    requirepass petclinic123
    appendonly yes
    maxmemory 100mb
    maxmemory-policy allkeys-lru
